# Generated by Django 4.2.7 on 2023-12-05 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='created_at',
            field=models.DateField(default='2023-12-01', verbose_name='date of creation'),
        ),
    ]
